### ISSUE TITLE
Wrong type of quotation marks in template sensors?

### ISSUE THREAD

**Issue by terpetter** [epenet/hassRenaultZE#1]
Hello,
I had to change some of the qoutation marks from double to single and vice versa.
This works for me in Home Assistant 0.86.3:

 - platform: template
    sensors:
      mycar_plugged:
        value_template: "{{ state_attr('sensor.mycarbattery' , 'plugged') }}"
        friendly_name: "Plugged"
  - platform: template
    sensors:
      mycar_charging:
        value_template: "{{ state_attr('sensor.mycarbattery' , 'charging') }}"
        friendly_name: "Charging"
  - platform: template
    sensors:
      mycar_remaining_range:
        value_template: "{{ state_attr('sensor.mycarbattery' , 'remaining_range') }}"
        friendly_name: "Range"
        unit_of_measurement: 'km'

**Comment by toby17780** [comment]
Hello, 
same here - with this changes it works for me, too!

**Comment by epenet** [comment]
Strange, it's working ok for me in 0.84.6.
However, with two users affected, I've updated the documentation anyway.

Happy to know the home assistant sensor is getting used...
