### ISSUE TITLE
batteryTemperature not available

### ISSUE THREAD

**Issue by oncleben31** [epenet/hassRenaultZE#13]
Since the PR #12 is merged, you expect to have `batteryTemperature` in the json from the API.
I have an error related to that as it seems I don't have this key in the API response.
Perhaps link to the model.

**Comment by epenet** [comment]
batteryTemperature appeared, and then disappeared after a few days.
I think if the sensor doesn't exist we can just ignore it completely at this stage. Can you update the PR to just remove the else statement?

**Comment by epenet** [comment]
Merged PR #14
