### ISSUE TITLE
New Reanault app and now I cannot connect anymore

### ISSUE THREAD

**Issue by niso01** [epenet/hassRenaultZE#2]
Love your contribution to HA with this sensor. Today I got a message that the existing app is not supported anymore and after that the renaultze sensor cannot connect anymore. I get the following error message:

Update failed: 'RestrictedCountryException'
9:08 PM custom_components/renaultze/sensor.py (ERROR) - message first occured at 8:28 PM and shows up 41 times

**Comment by toby17780** [comment]
same here...

**Comment by epenet** [comment]
You'll need to provide more information about your issue, as it is still working correctly here.
In particular, since the error is "RestrictedCountryException", which country are you connecting from? I'm based in France.

Do you still connect through https://www.services.renault-ze.com/?
Does it stay there or is there a redirect onto another site?

You may need to run something like Firefox Development Tools to trace the requests.
I will also accept GIT pull requests.

**Comment by niso01** [comment]
I am based in Sweden. When I try to login at https://www.services.renault-ze.com/ I get the following message (translated from Swedish):
------------------------------------------------------------------------------------------------------
Your connected Z.E services will be moved to a new app
MY Z.E. the app is no longer available, it has been replaced by the app MY Renault
Continue to use connected Z.E. services by:
1. Download the MY Renault app for free
2. Create a MY Renault account
3. Synchronize your car with the VIN number and activation code you received in an email

(Link from a button)  https://myr.renault.pt/ze_redirection.html?os=web&country=se&lang=sv

-------------------------------------------------------------------------------------------------------

The new app is called "My Renault" and if follow the link above and logon I will in the end end up at the follow url:  https://myr.renault.se/

**Comment by epenet** [comment]
Does the new application work in a browser? or only on a phone application?
If it works in a browser, I might be able to reverse-engineer the new application but I would need access to a real account.

Since France has not been migrated to the new app (yet?), maybe someone wants to share his account (set a temporary password and send me the credentials via private message)

**Comment by niso01** [comment]
I cannot get any charging info from the web, only from the app. This is weird. 
@toby17780 - what country are you connecting from and can you get any charging info in the web browser?

**Comment by toby17780** [comment]
I'm from Germany. But this Error was only one time - now after Update I have this one: https://github.com/epenet/hassRenaultZE/issues/3

**Comment by oncleben31** [comment]
@epent if you are in France you should be impacted now. I've the error message to migrate to MyRenault app 2 days ago.
Similar discussion on edent/Renault-Zoe-API#18

**Comment by niso01** [comment]
@epenet Let me know when and if you need som assistance.

**Comment by oncleben31** [comment]
reverse engineering API is not my thing. But as soon as you have a start I can support by doing python package or HA integration.

**Comment by oncleben31** [comment]
@epenet now we have a python package. As you have started to prototype even if you said you won't work on it before mid august, do you wan't to start something ? If you are not available and agree I can start a custom_component. We can share the energy.

**Comment by epenet** [comment]
I've created a new branch that I am working on: https://github.com/epenet/hassRenaultZE/tree/newApi

**Comment by epenet** [comment]
I've tested what I could outside Home Assistant. I need to rebuild my server before I can test it inside Home Assistant.

There is one new configuration setting available: "android_lng" which default to fr_FR. If you are not based in France you might need to override the value in your configuration file.
Also, I have removed the "deep update" option.

**Comment by epenet** [comment]
I've merged the new code into the main branch: https://github.com/epenet/hassRenaultZE

Please don't hesitate to download, test and confirm it's all working for you...

**Comment by oncleben31** [comment]
Tested. Need some updated to make it work in HA. PR #6 is waiting for review.

**Comment by epenet** [comment]
PR #6 reviewed and merged.

**Comment by oncleben31** [comment]
I think we can close the issue now.
