### ISSUE TITLE
Battery / Mileage update failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by toby17780** [epenet/hassRenaultZE#22]
Hallo zusammen,

seit 2 Tagen habe ich folgende Fehlermeldung im Log und es wird nichts mehr angezeigt:

> 2020-04-04 21:57:01 WARNING (SyncWorker_2) [custom_components.renaultze.sensor] Battery update failed: Traceback (most recent call last):
>   File "/config/custom_components/renaultze/sensor.py", line 152, in update
>     jsonresult = self._vehicle.battery_status()
>   File "/usr/local/lib/python3.7/site-packages/pyze/api/kamereon.py", line 204, in battery_status
>     return self._get('battery-status')
>   File "/usr/local/lib/python3.7/site-packages/pyze/api/kamereon.py", line 184, in _get
>     response.raise_for_status()
>   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/kmr/remote-services/car-adapter/v1/cars/VF1AG00000000000/battery-status
> 
> 2020-04-04 21:57:01 WARNING (SyncWorker_2) [custom_components.renaultze.sensor] Mileage update failed: Traceback (most recent call last):
>   File "/config/custom_components/renaultze/sensor.py", line 159, in update
>     jsonresult =  self._vehicle.mileage()
>   File "/usr/local/lib/python3.7/site-packages/pyze/api/kamereon.py", line 217, in mileage
>     return self._get('cockpit')
>   File "/usr/local/lib/python3.7/site-packages/pyze/api/kamereon.py", line 184, in _get
>     response.raise_for_status()
>   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/kmr/remote-services/car-adapter/v1/cars/VF1AG00000000000/cockpit

Noch jemand oder liegt es an meinem Account?

**Comment by age-creator** [comment]
I have the same issue.
Including the following:

> HTTPError: 504 Server Error: Gateway Time-out for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/kmr/remote-services/car-adapter/v1/cars/VF1AGxxxxxxxxxxxx/cockpit

> HTTPError: 500 Server Error: Internal Server Error for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/kmr/remote-services/car-adapter/v1/cars/VF1AGxxxxxxxxxxxx/cockpit

> HTTPError: 403 Client Error: Forbidden for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/kmr/remote-services/car-adapter/v1/cars/VF1AGxxxxxxxxxxxx/cockpit

> HTTPError: 401 Client Error: Unauthorized for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/kmr/remote-services/car-adapter/v1/cars/VF1AGxxxxxxxxxxxx/cockpit

**Comment by JeedHome44** [comment]
Bonjour,

On vient de me dire que Renault a fermé son ancien serveur d’authentification la semaine dernière.

Pourriez vous mettre à jour le GitHub pour qu’il marche avec le nouveau serveur Renault?

Le problème vient de la...

Merci.

**Comment by epenet** [comment]
Hi,

Indeed, Renault removed the v1 endpoints over the weekend, and we need to move to the v2 endpoints (available in pyze 0.4.0).
If someone wants to provide a PR, I'll happilly merge or I'll do it myself later this week.

**Comment by toby17780** [comment]
Ok, i've changed the code - can you give me the rights to provide a PR?
In my environment it works now without problems. ;-)

**Comment by epenet** [comment]
You should fork directly from Github, then push your branch to your Github fork, then request PR from your Github fork to this repository.
If not, you'll have to send me the file or the diff and I will merge it.

**Comment by epenet** [comment]
Merged PR #23
