### ISSUE TITLE
Platform error sensor.renaultze - No module named 'pyze'

### ISSUE THREAD

**Issue by JeedHome44** [epenet/hassRenaultZE#25]
Hello,

i download the new git you upgrade tomorrow.
i do what README say in my configuration.yaml

But, when i test configuration before reboot, i have this:

**Platform error sensor.renaultze - No module named 'pyze'**

What i have to do?

**Comment by epenet** [comment]
It seems you are missing the pyze module.
Did you copy the correct "manifest.json" on your server? Home Assistant uses that to download (or upgrade) the module.

**Comment by JeedHome44** [comment]
yes I copied the renaultze folder with the 3 files including the one you modified 14 hours ago

i do this i my configuration.yaml:

sensor:
# Renault ZE
  - platform: renaultze
    name: ZE40
    username: !secret mail_icloud
    password: !secret renaultze_password
    vin: !secret renaultze_vin

i tested my log in myrenault.com. it's good

**Comment by epenet** [comment]
I suggest you post your whole log file.
Maybe there is an indication why the pyze download didn't work...

**Comment by JeedHome44** [comment]
How do we do that? I don't know much about it

**Comment by JeedHome44** [comment]
I restarted my Hassio without adding the sensor in the configuration.yaml file and then I added the lines in the configuration.yaml file and by doing a configuration test it tells me that everything is ok! You must therefore add your renaultze folder, then restart Home assistant.
