### ISSUE TITLE
adaption needed for current home assistant

### ISSUE THREAD

**Issue by slankes** [epenet/hassRenaultZE#3]
The sensor still works for me but I had to shuffle files around as home assistant now requires each custom component to be in it's own subdirectory.

```
custom_components/renaultze/renaultzeservice
custom_components/renaultze/renaultzeservice/__init__.py
custom_components/renaultze/renaultzeservice/renaultzeservice.py
custom_components/renaultze/sensor.py
custom_components/renaultze/__init__.py
```
the renaultze/__init__.py is crucial for the sensor to work with HA 0.92 and only contains a remark:

```"""The renaultze sensor"""```

**Comment by epenet** [comment]
Thanks @slankes. I finallly got round to updating this.
