### ISSUE TITLE
Sensor not showing up

### ISSUE THREAD

**Issue by crohot** [epenet/hassRenaultZE#33]
Hi and thanks for the nice contribution!

I followed all steps as you suggested but the sensor you mention is not showing up.
There is only a warning message:
`You are using a custom integration for renaultze which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Connection lost. Reconnecting…
`
But besides from that no errors are showing up. Do you have any suggestions what to check?
Thank you!

**Comment by crohot** [comment]
Found something else:
`Platform error sensor.renaultze - No module named 'pyze'`

**Comment by epenet** [comment]
The pyze module should get downloaded and installed automatically the first time you start Home Assistant with the hassRenaultZE.
Maybe you are simply impatient...

Also, did you enable debug logging in the configuration?
```
logger:
  default: warn
  logs:
    custom_components.renaultze.sensor: debug
```

**Comment by crohot** [comment]
Hi, i did wait overnight and i restarted again but no luck. 
Where can i find the logs of the debug mode?

**Comment by epenet** [comment]
The message about `You are using a custom integration for renaultze` is normal, and only appears once, but I am not sure where `Connection lost. Reconnecting… ` comes from.

Did you correctly copy the four files (\_\_init\_\_.py, manifest.json, sensor.py, services.yaml) ?

You'll need to give more information about your Home Assistant setup (version, OS, etc.).
Are you able to see the install logs? If you are using a manual install with a virtual environment, maybe you can install the pyze module manually using pip?

**Comment by crohot** [comment]
There was no services.yaml in the zip i downloaded from github! I now put that one in the custom components. 

This is my System:

arch | armv7l
chassis | embedded
dev | false
docker | true
hassio | true
host_os | HassOS 3.13
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.114-v7
python_version | 3.7.7
supervisor | 227
timezone | Europe/Berlin
version | 0.110.1
virtualenv | false

**Comment by epenet** [comment]
Please add a k_account_id setting to your configuration (empty string should be ok)
And if you get the `No module named 'pyze'` error again, please check HassOS documentation to manually install the module.

**Comment by crohot** [comment]
Added a random ID, not working. I don´t know how to install pyze manually, so I´m out. Thank you anyway.

**Comment by epenet** [comment]
You can try to first add this module: https://github.com/home-assistant/hassio-addons-development
Though I've never used it, it should give you an option to manually install pyze

**Comment by crohot** [comment]
The k_account_id was empty until i tried it with something random. 
I was able to add the module you mentioned but it only offers me to install:

Custom deps deployment
Manage custom python modules in Home Assistant deps

Remote API proxy
Remote API proxy for Home Assistant

Remote ptvsd debugger
Remote Debug proxy for Supervisor/ptvsd

I really appreciate your patience, as i am very impacient with things that don´t automagically work ootb ;-)

**Comment by epenet** [comment]
If you select "Manage custom python modules in Home Assistant deps", are you there able to install pyze?

**Comment by crohot** [comment]
New error messages:

`Battery update failed: Traceback (most recent call last): File "/config/custom_components/renaultze/sensor.py", line 195, in update jsonresult = self._vehicle.battery_status() File "/usr/local/lib/python3.7/site-packages/pyze/api/kamereon.py", line 229, in battery_status return self._get('battery-status', 2) File "/usr/local/lib/python3.7/site-packages/pyze/api/kamereon.py", line 202, in _get response.raise_for_status() File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/5x5jc6ttjrp49jtf/kamereon/kca/car-adapter/v2/cars/VF1AG000761438208/battery-status?country=GB`

**Comment by epenet** [comment]
So pyze is good now.
Did you set the k_account_id to empty? or is this where 5x5jc6ttjrp49jtf comes from?

**Comment by crohot** [comment]
Oh, nice. 
The random id was a try, i deleted it now but if i check the config i get this error again:
`Invalid config for [sensor.renaultze]: string value is None for dictionary value @ data['k_account_id']. Got None. (See ?, line ?). 
`

**Comment by epenet** [comment]
Can you please copy paste your config?

I assume you have written it with nothing at the end (which gets converted to None)
```yaml
    k_account_id: 
```

If you know your k_account_id, it should look like this:
```yaml
    k_account_id: YYYYYYYY
```

If you don't know it, then remove the k_account_id line completely, or force it as an empty string (with quotes)
```yaml
    k_account_id: ""
```

**Comment by crohot** [comment]
Oh, wow, with the "" i get a valid config! But currently, the Entities Card does not show any value.
What config do you want to see? My configuration.yaml or the developer-tools/info?

**Comment by epenet** [comment]
I don't know what you mean about entities card - I always use "development tools" > "states" to check my sensors.

The default integration generates just a single sensor (the battery %) with lots of additional attributes.
To convert the attributes to individual sensors you need to create template sensors.

**Comment by crohot** [comment]
I meant the card to display something on the dashboard. It still says "None" for every value.
But checking "development tools" > "states" as you suggest, i get the following:
`battery_available_energy: false
charging: false
charge_status: Not charging or plugged in
last_update: '2020-06-12T14:21:33+02:00'
plugged: false
plug_status: Unplugged
remaining_range: 289
charging_power: 0
charging_remaining_time: null
mileage: 11987
hvac_status: 'off'
outside_temperature: 32
unit_of_measurement: '%'
friendly_name: FZO320E`

And this is looking much better!

**Comment by epenet** [comment]
I think we can close this thread now. If you have questions about the Home Assistant UI, then it would be better handled on the Home Assistant forums.

**Comment by crohot** [comment]
Its indeed working now! Thank you very much for your support!
