### ISSUE TITLE
unknown sensor status

### ISSUE THREAD

**Issue by JeedHome44** [epenet/hassRenaultZE#35]
Hello,

No more updates since July 1 at 12:30.
Renault changed something?

The status of my sensor is now unknown after a reboot.
However, I haven't changed anything on my MyRenault account. I renewed my services in June and it continued to work.

**Comment by johan12345** [comment]
It seems there was a change on Renault's side, using the latest version of pyze should fix the problem: https://github.com/jamesremuscat/pyze/commit/a05dfac0a9fb1e287b4df9ed7c911cb0f5e8b3d5

**Comment by epenet** [comment]
I've just merged PR #36 which includes the required fix.

**Comment by JeedHome44** [comment]
using the developer version of your GitHub with actions, what should I change in the file to keep all the functions?

**Comment by epenet** [comment]
The developer version has been merged into the master version - so just use that now.

**Comment by JeedHome44** [comment]
Thank you

**Comment by epenet** [comment]
It's also available as release [v2.0.1](https://github.com/epenet/hassRenaultZE/releases/tag/v2.0.1)
