### ISSUE TITLE
Charging attribute : issue or feature ?

### ISSUE THREAD

**Issue by PysX** [epenet/hassRenaultZE#39]
Hello, 

"Charging" attribute is set to true or false if "Charge State" > 0 by : `self._attrs[ATTR_CHARGING] = jsonresult['chargingStatus'] > 0`

Is this a feature ? Because, charging status could have values between 0 and 1. And for my perception this values are "not charging" (charging = false). https://github.com/jamesremuscat/pyze/blob/05dbe5d28ff73ecf0553bc33c7ab5913cb786cfe/src/pyze/api/kamereon.py#L371
In my opinion only value 1.0 is "charging".  But it could be a position to set "charging" to true when value > 0 and let people check "charge state" for the "real status".

What do you think about it ?
Thanks for your time.

**Comment by epenet** [comment]
Hi @PysX,

Can you update to [v3.0.0](https://github.com/epenet/hassRenaultZE/releases/tag/v3.0.0) and see if that is still an issue?

**Comment by PysX** [comment]
Hi @epenet, what a nice upgrade !

v3.0.0rc2 installed and running. I will plug my car tomorrow and let you informed of results for charge state / status.

i will monitor other sensors to review if they are working like in the v2.x.
Actuallay, one sensor is missing ("charging remaining time"), may be it's a sensor's state and the car need to be in charging state. I will check that too.

Thanks for your work!

**Comment by epenet** [comment]
Keep me posted about "charging remaining time". It's true that it's not one I've paid attention to so I may have missed it.

**Comment by PysX** [comment]
Hi !
Since Saturday, the v3 rc2 is working great on my home assistant and the subject of this issue is closed.

About charging remaining time, i do not have the sensor. I tried to remove / reconfigure the integration during charge: no effect.

I will provide more info with debug log and some testing.

**Comment by PysX** [comment]
Ok, some testing with conclusion that's just a missing "entities.append" !
I suggest the following PR : #52 , tested on my installation.

I you want you can close this issue ! Thanks !

**Comment by epenet** [comment]
Nice spot.
Thanks @PysX
