### ISSUE TITLE
Gigya returned error 403007, error when setting up component 

### ISSUE THREAD

**Issue by myhrmans** [epenet/hassRenaultZE#43]
Restarted Home Assistant now without any changes to the ZE component and got the following error:

`Error while setting up renaultze platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/config/custom_components/renaultze/sensor.py", line 102, in async_setup_platform
    g.account_info()
  File "/usr/local/lib/python3.8/site-packages/pyze/api/credentials.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyze/api/gigya.py", line 77, in account_info
    raise_gigya_errors(response_body)
  File "/usr/local/lib/python3.8/site-packages/pyze/api/gigya.py", line 123, in raise_gigya_errors
    raise RuntimeError(
RuntimeError: Gigya returned error 403007: Invalid namespace &#39;accounts&#39; or method &#39;getAccountInfo&#39; or you do not have the required permissions to call it.`

Anyone experienced this?

**Comment by epenet** [comment]
403007 is an error from Gigya, so I assume the problem is on the Renault side.

You can also try to run the Pyze module directly in CLI mode. I expect it will be the same error there.

**Comment by epenet** [comment]
Note from Gigya documentation: https://developers.gigya.com/display/GD/Response+Codes+and+Errors

403007 | Permission denied | Returned  when a user lacks the necessary permissions to perform the requested  action, or when the user's credentials are not configured properly.

**Comment by age-creator** [comment]
I got the same error starting around 5 hours ago.

**Comment by myhrmans** [comment]
> I got the same error starting around 5 hours ago.

@age-creator did you fix it? I have not been able to find what is wrong. What's your location and car?
Mine is Sweden ZE50 R135

**Comment by toby17780** [comment]
Same error since a couple of hours. Anybody checked the pyze module directly?

**Comment by age-creator** [comment]
> > I got the same error starting around 5 hours ago.
> 
> @age-creator did you fix it? I have not been able to find what is wrong. What's your location and car?
> Mine is Sweden ZE50 R135

No, I didn't have time to look into this further, but it looks again as an change to the authentication which is maybe implemented in phases. Car: NL ZE40 R110

**Comment by myhrmans** [comment]
> Same error since a couple of hours. Anybody checked the pyze module directly?

@toby17780 
Yes I get this error from pyze directly using the same values as before and working when logging out and of the app:

`raise RuntimeError(
RuntimeError: Gigya returned error 403042: invalid loginID or password`

**Comment by myhrmans** [comment]
Fixed in pull [#79](https://github.com/jamesremuscat/pyze/pull/79). Waiting for a updated pipy package to resolve the issue with this repo.

**Comment by myhrmans** [comment]
Resolved in #44

**Comment by myhrmans** [comment]
Resolved in #44
