### ISSUE TITLE
Add repo to HACS

### ISSUE THREAD

**Issue by etobi** [epenet/hassRenaultZE#48]
For easy installation and updating it would be awesome if this repo would be available in HACS.
Any chance?

**Comment by epenet** [comment]
There is an active pull request on [Home Assistant Core](https://github.com/home-assistant/core/pull/39605)

**Comment by etobi** [comment]
awesome.

**Comment by epenet** [comment]
It looks like the merge into the core is likely to take a while, so I'll make the new custom_component available on this repository in the meantime!

**Comment by epenet** [comment]
Hi @etobi,

Do you want to review the latest code from [hacs_blueprint branch](https://github.com/epenet/hassRenaultZE/tree/hacs_blueprint) before I submit it to HACS?

**Comment by etobi** [comment]
I cant do a real "review" - but at least i will install and test it

**Comment by etobi** [comment]
I just installed the component from the hasc_blueprint branch.
First I stucked with the API-Keys and the pyze documentation. I will file an issue there.
Also the climate entity seems not to wirk - might be an issue for me only - i cant start the AC from the original MyRenault-App either.

beside of that: awesome. works great :-)

**Comment by epenet** [comment]
If you can't start the AC from the original MyRenault-App, then I think it won't be possible to make it work inside Home Assistant either. Maybe something to discuss with Renault...

Regarding the API keys, I wish pyze would implement a way to load them via the API but that's his choice!
