### ISSUE TITLE
v3.0.0: unknown error when logging in

### ISSUE THREAD

**Issue by johan12345** [epenet/hassRenaultZE#49]
When setting up the new version with the config flow, it gives me the error message "Unknown error occurred". In the log, I find the following error:

```
File "/home/alarm/.homeassistant/custom_components/renault/config_flow.py", line 66, in async_step_credentials
    if not await self.pyzeproxy.attempt_login():
  File "/home/alarm/.homeassistant/custom_components/renault/pyzeproxy.py", line 69, in attempt_login
    self._gigya.login,
AttributeError: 'NoneType' object has no attribute 'login'
```

**Comment by epenet** [comment]
Thanks @johan12345
Looks like I broke the config_flow in the final stages. Can you try the latest code from develop branch before I release it as v3.0.1?

**Comment by johan12345** [comment]
Thanks, it works now!
