### ISSUE TITLE
Cannot call services from HomeAssistant

### ISSUE THREAD

**Issue by cris88** [epenet/hassRenaultZE#53]
I got error every time I call a service.

Example (I put wrong vin only for the print):
![image](https://user-images.githubusercontent.com/1536899/96038790-976b3680-0e5f-11eb-902f-c0ac16634ac4.png)

Error:
![image](https://user-images.githubusercontent.com/1536899/96038922-c84b6b80-0e5f-11eb-99c6-7dd1655ef61c.png)

thanks.

**Comment by epenet** [comment]
Can you please try latest dev? It should be fixed in 7bac25ff9cb913dddffab9abd4d982b252f4961d

**Comment by cris88** [comment]
it's solved.

The only service I can't test was renault.charge_set_schedules.
Can you provide an example payload yaml for this service? Thanks

**Comment by WinkelB** [comment]
@cris88 
example payload for renault.charge_set_schedules:
`vin: vf1xxxxxxxxxxxxxx
schedules:
  id: 1
  activated: true
  monday:
    startTime: 'T12:00Z'
    duration: 15
  tuesday:
    startTime: 'T12:00Z'
    duration: 15
  wednesday:
    startTime: 'T12:00Z'
    duration: 15
  thursday:
    startTime: 'T12:00Z'
    duration: 15
  friday:
    startTime: 'T12:00Z'
    duration: 15
  saturday:
    startTime: 'T12:00Z'
    duration: 15
  sunday:
    startTime: 'T04:30Z'
    duration: 420
`

**Comment by WinkelB** [comment]
The Services are now working in the latest dev Version (v3.0.0-rc3) Great Job!

**Comment by epenet** [comment]
@cris88, I've updated @WinkelB's comment so that the YAML is formatted. It should make it easier to copy/paste

Also, you should notice at the bottom of your screenshot a link to "PREENCHER COM DADOS DO EXAMPLO"

**Comment by epenet** [comment]
@cris88 can we close this?

**Comment by cris88** [comment]
> @cris88 can we close this?

Hello @epenet , yes we can close. It's fully working. Thanks for your great job. 👍
