### ISSUE TITLE
Ignore Kamereon account without vehicle.

### ISSUE THREAD

**Issue by epenet** [epenet/hassRenaultZE#55]
OK during the config flow, I have to serial number at the last step. The first one didn't work and the second correspond to my Zoé.

_Originally posted by @oncleben31 in https://github.com/epenet/hassRenaultZE/issues/30#issuecomment-711086472_

**Comment by oncleben31** [comment]
I have look at the communication.
The two account have different ID and different types (`MYRENAULT` and `SFDC`). My vehicle is in the MYRENAULT. Could we ignore by default `SFDC` account ? Or is there some case where vehicule could be hosted in this account ?
