### ISSUE TITLE
battery temperature is missing

### ISSUE THREAD

**Issue by epenet** [epenet/hassRenaultZE#57]
I notice that battery temperature is missing. Is it normal ?

_Originally posted by @oncleben31 in https://github.com/epenet/hassRenaultZE/issues/30#issuecomment-711086472_

**Comment by epenet** [comment]
This is still available as an attribute on the battery sensor. Do you think it is useful to "upgrade" it to a full sensor?

**Comment by cris88** [comment]
> This is still available as an attribute on the battery sensor. Do you think it is useful to "upgrade" it to a full sensor?

Hello @epenet , yes I think it will be useful upgrade it to a fill sensor.

**Comment by oncleben31** [comment]
I like the idea to have a dedicated sensor.

**Comment by epenet** [comment]
Do you guys fancy providing a PR?

**Comment by oncleben31** [comment]
I can work on it.
