### ISSUE TITLE
Implement new client from jamesremuscat

### ISSUE THREAD

**Issue by epenet** [epenet/hassRenaultZE#8]
For the jamesremuscat module there is two ways of implementing it `cli`and `api`. So no need to use environment variables.
If we expect to have an official integration in HA, having a module installable by pip is a prerequisite.

_Originally posted by @oncleben31 in https://github.com/epenet/hassRenaultZE/pull/6#issuecomment-515904585_

**Comment by epenet** [comment]
@oncleben31 
If you take a look at my fork from [jamesremuscat](https://github.com/epenet/pyze/tree/master/src/pyze), I've created a "test.py" with a "credentials.json" but I can't get it to work.
I'll try and work on it some more this week.

Once I'm happy with it in "test" mode, then I'll adapt the home assistant integration to make proper use of it.

**Comment by oncleben31** [comment]
OK I can try on my side too.

**Comment by epenet** [comment]
I've made further testing, and got it working.
There a small issue about "simplejson" versus "json" (python3 versus python2)

I've updated the test.py, which now seems to work.
Now I need to prepare some PR for james

**Comment by oncleben31** [comment]
You can perhaps use this template for custom_components: https://github.com/custom-components/blueprint/

**Comment by epenet** [comment]
I'm waiting for james to merge [PR7](https://github.com/jamesremuscat/pyze/pull/7) and publish the updated version, then I should be able to work on this.

**Comment by jamesremuscat** [comment]
PyZE `0.2.0` just got published to PyPI.

**Comment by oncleben31** [comment]
It's working. Bravo.
And `battery_temperature` is back.
