### ISSUE TITLE
add a manifest.json for HACS compatibility

### ISSUE THREAD

**Issue by oncleben31** [epenet/hassRenaultZE#9]
Can you add a manifest.json to allow to install and update your custom component with HACS ?

**Comment by epenet** [comment]
@oncleben31 I have added the manifest.json, but I would prefer to finish the integration with [jamesremuscat's integration](https://github.com/jamesremuscat/pyze) before pushing stuff to HACS.

I am also hoping to rename as hassMyRenault.

**Comment by oncleben31** [comment]
Good idea for renaming the components.

**Comment by oncleben31** [comment]
What about making it an official integration when it will be tested by a serious number of users?

**Comment by oncleben31** [comment]
Thank you for the manifest. We can now import this repo in HACS to have update as soon as you push a modification
